//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCX.Models.Tables
{
    using System;
    using System.Collections.Generic;

    public partial class CustomerRoleDuration
    {
        [System.ComponentModel.DataAnnotations.Key]
        public long CustomerRoleDurationID { get; set; }
        public virtual Customers CustomerID { get; set; } // FK
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime CreatedDate { get; set; }
        public long ConvertedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }

    }
}
