//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCX.Models.Tables
{
    using System;
    using System.Collections.Generic;

    public partial class Potential
    {
        public string CustomerID { get; set; }
        public string Closingdate { get; set; }
        public string Accountname { get; set; }
        public string Stage { get; set; }
        public string IsDeleted { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Modifiedby { get; set; }



    }
}
