//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCX.Models.Tables
{
    using MCX.Models.Tables;
    using System;

    public partial class Task
    {
        public int TaskId { get; set; }
        public Nullable<long> LoginId { get; set; }
        public string subject { get; set; }
        public System.DateTime endDateTime { get; set; }
        public string Createdby { get; set; }
        public string Modifiedby { get; set; }
        public string IsActive { get; set; }
        public string IsDeleted { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<System.DateTime> startDateTime { get; set; }
    
        public virtual Users User { get; set; }
    }
}
