//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCX.Models.Tables
{
    using System;
    using System.Collections.Generic;

    public partial class UserLoginLog
    {
        public long LoginLogID { get; set; }
        public string IPaddress { get; set; }
        public long loginID { get; set; }
        public System.DateTime createdDate { get; set; }
    }
}
